# Generated by Django 3.1.7 on 2022-11-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='a1',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='a2',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='a3',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='a4',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='a5',
            new_name='titulo',
        ),
    ]
